{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sharedLogic/1.0.0-local/sharedLogic-1.0.0-local.module",
    "group": "com.noonpayments",
    "module": "sharedLogic",
    "version": "1.0.0-local",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "sharedLogic-iosSimulatorArm64Main-1.0.0-local.klib",
          "url": "sharedLogic-iossimulatorarm64-1.0.0-local.klib",
          "size": 211006,
          "sha512": "ffa916672ce108a6fbdbfa4342b4bd9d22dc730ba1ef50aae2ca5f9a27d2464e4f9605ed790b3735a53e1932b4db951cb45844e2a0eedad91c458df6a15d27d6",
          "sha256": "167ab86529cb426a751c1f55dd51150517ff3b43809c5ffc66397a8e34f970d7",
          "sha1": "2da784114e7a05cc12fa309e78d4f3425ef11859",
          "md5": "d66cb3ebf80b46276fedf925dd3b6a15"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "sharedLogic-iossimulatorarm64-1.0.0-local-sources.jar",
          "url": "sharedLogic-iossimulatorarm64-1.0.0-local-sources.jar",
          "size": 54772,
          "sha512": "91bf9bc5840416ead6a849a985078c747591cfcee2365f8cb26b9cbcba6bc520449bbe3907dbbca8ee59fbc7dfd20b516e0a14dbf33b65a0cb0bacfe1d1b9478",
          "sha256": "41a4dc80237ab6fa684802ffb14828368c0c640ddaf1009fa450a007b6ec9575",
          "sha1": "72a7fae9262c877ebda49a9c72e5e9273cba50db",
          "md5": "6fb414b10b3a0c42282c5f69d835b3ba"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "sharedLogic-iossimulatorarm64-1.0.0-local-metadata.jar",
          "url": "sharedLogic-iossimulatorarm64-1.0.0-local-metadata.jar",
          "size": 4434,
          "sha512": "f29257d3bd5bcc0911e6734ee925613bc3be12d8d445f4171c7098a9e7a154f57d9f64ceb57f4af97fbed3b165c0a82a26c7d15f246e101bd1222a44aedcbd3b",
          "sha256": "f31f78c38cf254bd92b3258048cb8a5273e3ad2a4adc4b25e42f95825717cf93",
          "sha1": "f6f926789fa9399934415541049a203252e964e1",
          "md5": "11e2b4dfa71caec300a5b4242982d646"
        }
      ]
    }
  ]
}
