{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sharedLogic/1.0.0-local/sharedLogic-1.0.0-local.module",
    "group": "com.noonpayments",
    "module": "sharedLogic",
    "version": "1.0.0-local",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sharedLogic.aar",
          "url": "sharedLogic-android-1.0.0-local.aar",
          "size": 252232,
          "sha512": "0f7c12663cdb75b9bf7e79213125d3081c2d44a69d1f08b8eb5137eb71089c3e75327e8eba60b2fdee3f1bdbca43fc299a8851e5368140c3112f878cafe64b8e",
          "sha256": "48807921c021beb0cdbfe409f76f11a00f41054dbba049f82fc6cf9912b76831",
          "sha1": "2fdadffe6be69b655e2004894365eed0c711bfb1",
          "md5": "88b5b0686c74da33a3ddae79aee8ed0f"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "sharedLogic.aar",
          "url": "sharedLogic-android-1.0.0-local.aar",
          "size": 252232,
          "sha512": "0f7c12663cdb75b9bf7e79213125d3081c2d44a69d1f08b8eb5137eb71089c3e75327e8eba60b2fdee3f1bdbca43fc299a8851e5368140c3112f878cafe64b8e",
          "sha256": "48807921c021beb0cdbfe409f76f11a00f41054dbba049f82fc6cf9912b76831",
          "sha1": "2fdadffe6be69b655e2004894365eed0c711bfb1",
          "md5": "88b5b0686c74da33a3ddae79aee8ed0f"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "sharedLogic-android-1.0.0-local-sources.jar",
          "url": "sharedLogic-android-1.0.0-local-sources.jar",
          "size": 54175,
          "sha512": "d9db3ebabff9afbe6459b36fc808c8e4be158251219e06fd7c2d5a69daa53839899094a58d21564caaff14627e5d8b32ca7bd90bfa3e0ec6f4f1d33b9fba4dee",
          "sha256": "efbee21a9853c2fbf5f8ed236014781b50a495de837e6cb40193101929d7ae4b",
          "sha1": "182207c525ffe2b1eadec352f28ced5999363389",
          "md5": "b10b0977c4cc000781232d5a85eee2d3"
        }
      ]
    }
  ]
}
