{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sharedLogic/1.0.4/sharedLogic-1.0.4.module",
    "group": "com.noonpayments",
    "module": "sharedLogic",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "sharedLogic-iosSimulatorArm64Main-1.0.4.klib",
          "url": "sharedLogic-iossimulatorarm64-1.0.4.klib",
          "size": 193387,
          "sha512": "6166bbb68166bea5c22dbcc78b1f9cf56ffabb8b8da4af7777a219d20485d948d8d023f139b0b71672ed1aab0dd0de0f0e065df46af2cf633b207d35ac01a5d0",
          "sha256": "040339c78c5809c3c35972191be3725ecb35f19262c194d18ad94d93034fe5d7",
          "sha1": "ef6bc7ee7f5c71afd71f144ec11a1124e13b7d7e",
          "md5": "393ea7eab69e569ee0dda68aa9454f12"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "sharedLogic-iossimulatorarm64-1.0.4-sources.jar",
          "url": "sharedLogic-iossimulatorarm64-1.0.4-sources.jar",
          "size": 48213,
          "sha512": "4073f7d594a598c086e327dbfbb24dc264bc093989ea401ab3e709e5fac6e44128975897d39933e527457ab5cb55dd5f86a81dfa2687f1326e194babf8976920",
          "sha256": "167b2d6596b6828b23c27223565424c6507722b09b2ddb9dccd2e2fd12b1e2c1",
          "sha1": "d073530b98b81fc68381893a192b97e6c0cef8bd",
          "md5": "3383288b5ca6edd2c5029deae28375cd"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "sharedLogic-iossimulatorarm64-1.0.4-metadata.jar",
          "url": "sharedLogic-iossimulatorarm64-1.0.4-metadata.jar",
          "size": 4434,
          "sha512": "f29257d3bd5bcc0911e6734ee925613bc3be12d8d445f4171c7098a9e7a154f57d9f64ceb57f4af97fbed3b165c0a82a26c7d15f246e101bd1222a44aedcbd3b",
          "sha256": "f31f78c38cf254bd92b3258048cb8a5273e3ad2a4adc4b25e42f95825717cf93",
          "sha1": "f6f926789fa9399934415541049a203252e964e1",
          "md5": "11e2b4dfa71caec300a5b4242982d646"
        }
      ]
    }
  ]
}
