{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sharedLogic/1.0.5/sharedLogic-1.0.5.module",
    "group": "com.noonpayments",
    "module": "sharedLogic",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "sharedLogic-iosArm64Main-1.0.5.klib",
          "url": "sharedLogic-iosarm64-1.0.5.klib",
          "size": 274831,
          "sha512": "d96af5970b83153a4485d329dff6e6d2bdb99ec3675310ac03be3ffe7cd55abd0f80f61ff7849fe8e53eb142471cc6dc7985b28acc8cc2b46c8ba14ae6a5156b",
          "sha256": "418efb831499e0823e78621eca2f3c7a8a1789c12b0699b094970443dc74246d",
          "sha1": "ca56d2f7879de673a3ef026e2acae5d86fe67922",
          "md5": "306d24fb1acb55566f0986d317bd6e51"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "sharedLogic-iosarm64-1.0.5-sources.jar",
          "url": "sharedLogic-iosarm64-1.0.5-sources.jar",
          "size": 62908,
          "sha512": "e0321d825251450ecbff73762ef396a90289c3a78fee66af465d1cd01d16c32ee5374048113ffe3358e39353b0fc69f1e90e47bee14b086ddc1fd2c394391fbb",
          "sha256": "09b27a4062bfc3de319aeb41f1c6c01873667ce4eb4ab77a49fb588af710e67e",
          "sha1": "da7da2aa694c0307ef8f3ae923951f332ce6bc00",
          "md5": "10f7ca93874460f3ce12500fba7d3de9"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "sharedLogic-iosarm64-1.0.5-metadata.jar",
          "url": "sharedLogic-iosarm64-1.0.5-metadata.jar",
          "size": 5172,
          "sha512": "93e330a8d98bda3249e92950c8f11264cec66edbcae7b1b9c5bce98be2cc59bf5dd9597434dc180033444e65579775662bc34a4d9acbe1745b01028d28eff588",
          "sha256": "2caf0a469ec98af3094525e5efcd34830936392b5636bc6ef5f4e94c67f115fe",
          "sha1": "f0901ea81350268b991bdfcf5fb857a4aa442e7c",
          "md5": "003dcdf8860a3e0f807fb5c44348c523"
        }
      ]
    }
  ]
}
